name: example
description: Examples for mardux.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # redux: ^4.0.0
  flutter_redux: ^0.6.0
  http: ^0.12.0+4
  mardux:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true
